Pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('interests', views.interests, name="interests"),
    path('matakuliah', views.matakuliah, name="matakuliah"),
    path('listmatkul', views.listmatkul, name="listmatkul"),
    path('hapusMatkul/<str:pk>', views.hapusMatkul, name="hapusMatkul"),
    path('namamatkul', views.namaMatkul, name="namamatkul")
]

home/models.py
from django.db import models

# Create your models here.


YEAR_CHOICES = (
    ('2020', '2020'),
    ('2019', '2019'),
)

CLASS_CHOICES = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
    ('G', 'G'),
    ('H', 'H'),
    ('I', 'I'),
    ('J', 'J'),
    ('K', 'K'),
    ('L', 'L'),
    ('M', 'M'),
)

SKS_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)

class Kuliah(models.Model): #Representasi database
    matkul = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    jumlahSks = models.CharField(max_length=6, choices=SKS_CHOICES, default='1')
    deskripsi = models.TextField(max_length=200)
    tahun = models.CharField(max_length=6, choices=YEAR_CHOICES, default='2020')
    kelas = models.CharField(max_length=6, choices=CLASS_CHOICES, default='A')

home/forms.py
from django import forms

YEAR_CHOICES = (
    ('2020', '2020'),
    ('2019', '2019'),
)
CLASS_CHOICES = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
    ('G', 'G'),
    ('H', 'H'),
    ('I', 'I'),
    ('J', 'J'),
    ('K', 'K'),
    ('L', 'L'),
    ('M', 'M'),
)
SKS_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)

class KuliahForm(forms.Form):
    matkul = forms.CharField(label="Mata Kuliah", max_length=100)
    dosen = forms.CharField(label="Dosen", max_length=100)
    jumlahSks = forms.ChoiceField(label="Jumlah SKS", choices=SKS_CHOICES)
    deskripsi = forms.CharField(label="Deskripsi Kuliah",max_length=200, widget=forms.Textarea)
    tahun = forms.ChoiceField(label="Tahun", choices=YEAR_CHOICES)
    kelas = forms.ChoiceField(label="Kelas", choices=CLASS_CHOICES)

home/views.py
from django.shortcuts import render, redirect
from .forms import KuliahForm
from .models import Kuliah

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def interests(request):
    return render(request, 'home/interests.html')

## Taken form django documentation
def matakuliah(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = KuliahForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            matkul = form.cleaned_data['matkul']
            dosen = form.cleaned_data['dosen']
            jumlahSks = form.cleaned_data['jumlahSks']
            deskripsi = form.cleaned_data['deskripsi']
            tahun = form.cleaned_data['tahun']
            kelas = form.cleaned_data['kelas']
            p = Kuliah(matkul = matkul, dosen=dosen, jumlahSks = jumlahSks, deskripsi =deskripsi, tahun=tahun,
                       kelas=kelas)
            p.save()
            return render(request, 'home/terimakasih.html')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = KuliahForm()
    return render(request, 'home/matakuliah.html', {'form': form})

def listmatkul(request):
    all = Kuliah.objects.all()
    return render(request, 'home/listmatkul.html', {'all':all})

def hapusMatkul(request, pk):
    kuliah = Kuliah.objects.get(id=pk)
    if request.method == "POST":
        kuliah.delete()
        return redirect("home:listmatkul")
    context= {'item':kuliah}
    return render(request, 'home/delete.html', context)

def namaMatkul(request):
    semua = Kuliah.objects.all()
    return render(request, 'home/namamatkul.html', {'all':semua})

templates/home/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="icon" href="{% static "image/makara-ui-fasilkom.png" %}">
    <title>Perancangan dan Pemograman Web Story</title>
</head>
<body>

    <header class="navigation">
            {% block navigation %}
            {% endblock %}
        </header>

    {% block content %}
    {% endblock %}
    <footer class="contact" id="kontak">
            <ul class="icons">
                <li><a href="https://www.instagram.com/ariasenacahya/" target="_blank"> <img src="{% static "image/instagram (1).png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
                <li><a href="https://twitter.com/ddelvo45" target="_blank"> <img src="{% static "image/twitter (1).png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
                <li><a href="https://www.linkedin.com/in/ariasena-cahya-ramadhani-98388a179/" target="_blank"> <img src="{% static "image/linkedin.png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
                <li><a href="https://steamcommunity.com/id/poopfodays/" target="_blank"> <img src="{% static "image/steam(1).png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
            </ul>
    </footer>
    <footer class="footer">
            <h1>2020 Faculty of Computer Science University of Indonesia</h1>
    </footer>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static "jscript/app.js" %}"></script>
</body>
</html>

templates/home/delete.html
{% extends 'home/base.html' %}
{% load static %}
{% block navigation %}
    <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav6"><a href="{% url 'home:matakuliah' %}">Mata Kuliah</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
            </div>
{% endblock %}
{% block content %}
    <section class="container6">
       <header class="containerJudul">
            <h1>Apakah anda yakin ingin menghapus mata kuliah tersebut?</h1>
        </header>
        <section class="buttonContainer">
            <form action="{% url "home:hapusMatkul" item.id %}" method="POST">
                {% csrf_token %}
            <a href="{% url 'home:listmatkul' %}"><button type="button" >Tidak</button></a>
            <button type="button"><input type="submit" name="Yakin" id="deleteconfirm"></button>
            </form>
        </section>
    </section>
{% endblock %}

templates/home/index.html
{% extends 'home/base.html' %}
    {% load static %}
    {% block navigation %}
            <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href = "#aku">About</a></li>
                    <li class="nav2"><a href = "#ilmu">Education</a></li>
                    <li class="nav3"><a href = "#pengalaman">Experiences</a></li>
                    <li class="nav4"><a href="#kemampuan">Skills</a> </li>
                    <li class="nav5"><a href="{% url 'home:interests' %}">Interests</a></li>
                    <li class="nav6"><a href="{% url 'home:matakuliah' %}">Mata Kuliah</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
                </div>
    {% endblock %}

    {% block content %}
        <section class="container1">
        <section class="landing" id="mendarat">
            <div class="center_text">
                <h1>Welcome to my website!</h1>
                <h2>Wanna know more about me?</h2>
            </div>
            <a href ="#aku"><button class = "tombol1">Click Here</button></a>
        </section>

        <section class="about" id="aku">
            <div class="foto2">
                <img src="{% static "image/sena.jpg" %}" class="sena" alt="">
            </div>
            <div class="akudanjudul">
                <div class="judul2"><p>About Me</p></div>
                <div class="tulisanaku">
                Hello! My Name is Ariasena Cahya Ramadhani. People often call me Sena. I am currently studying Computer Science at University of Indonesia. I love speaking with other people and also working as a team. I am interested in psychology and esports.
                </div>
            </div>

        </section>

        <section class="education" id="ilmu">
            <div class="foto3">
                <img src="{% static "image/pacil7.PNG" %}" class="fasilkom" alt="">
            </div>
            <div class="akudanjudul2">
                <div class="judul3"><div class="all_edu">
                    <div class="ui">
                        <p class="gelar">Bachelor of Computer Science</p>
                        <p class="institusi">University of Indonesia</p>
                    </div>
                    <div class="sma">
                        <p class="gelar">High School Diploma</p>
                        <p class="institusi">SMAN 99 Jakarta</p>
                    </div>
                    <div class="smp">
                        <p class="gelar">Middle School</p>
                        <p class="institusi">SMP Islam PB Soedirman</p>
                    </div>
                    <div class="sd">
                        <p class="gelar">Elementary School</p>
                        <p class="institusi">SD Islam PB Soedirman</p>
                    </div>
                </div></div>
                <div class="tulisanaku2">
                    Education
                </div>
            </div>
        </section>

        <section class="experiences" id="pengalaman">
            <div class="foto2">
                <img src="{% static "image/compe.jpg" %}" class="fasilkom" alt="">
            </div>
            <div class="akudanjudul">
                <div class="judul2"><p>Experiences</p>
                </div>
                <div class="pengalaman">
                    <div class="all_exp">
                         <div class="ui">
                             <p class="gelar">Human Resources Staff</p>
                             <p class="institusi">BEM Fasilkom UI</p>
                         </div>
                        <div class="sma">
                            <p class="gelar">Human Resources of Games and Competition</p>
                            <p class="institusi">Perak Fasilkom</p>
                        </div>
                        <div class="smp">
                            <p class="gelar">Indie Game Ignite Staff</p>
                            <p class="institusi">Compfest 12</p>
                        </div>
                        <div class="sd">
                            <p class="gelar">Liason Officer</p>
                            <p class="institusi">Wisuda Ganjil Fasilkom UI</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

         <section class="skills" id="kemampuan">
            <div class="foto3">
                <img src="{% static "image/skills1.PNG" %}" class="fasilkom" alt="">
            </div>
            <div class="akudanjudul2">
                <div class="judul3"><div class="all_edu">
                    <div class="ui">
                        <img src="{% static "image/css-3.png" %}" class="skillsgambar" alt="">
                        <h2>CSS</h2>
                    </div>
                    <div class="sma">
                        <img src="{% static "image/html-5.png" %}" class="skillsgambar" alt="">
                        <h2>HTML</h2>
                    </div>
                    <div class="smp">
                        <img src="{% static "image/java.png" %}" class="skillsgambar" alt="">
                        <h2>Java</h2>
                    </div>
                    <div class="sd">
                        <img src="{% static "image/python.png" %}" class="skillsgambar" alt="">
                        <h2>Python</h2>
                    </div>
                </div></div>
                <div class="tulisanaku2">
                    Skills
                </div>
            </div>
        </section>
        </section>
            {% endblock %}

templates/home/interests.html
{% extends 'home/base.html' %}
{% load static %}

    {% block navigation %}
            <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav6"><a href="{% url 'home:interests' %}">Interests</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
            </div>
    {% endblock %}

    {% block content %}
    <section class="container2">
        <div class="judulminat">
            <h3>These are the things I love</h3>
        </div>

        <section class="minat1">
            <div class="minatgambar1">
                <img src="{% static "image/gaming.jpg" %}" class="gaming" alt="">
            </div>
            <div class="minatTulisan1">
                <p> I love playing games. I usually play a lot of gacha games and occasionally some MMORPGs. Right now I usually
                play Arknights and Genshin Impact. Both games are quite fun, especially Arknights that has an Interesting
                Mechanics. I also love playing sandbox games like Terarria.</p>
            </div>
        </section>

        <section class="minat2">

        </section>
    </section>

    {% endblock %}

templates/home/jaga_jaga.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="icon" href="{% static "image/makara-ui-fasilkom.png" %}">
    <title>Perancangan dan Pemograman Web Story</title>
</head>
<body>

    <header class="navigation">
            <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="navbar-brand"><a href = "#aku">About</a></li>
                    <li class="navbar-brand"><a href = "#ilmu">Education</a></li>
                    <li class="navbar-brand"><a href = "#pengalaman">Experiences</a></li>
                    <li class="navbar-brand"><a href="#kemampuan">Skills</a> </li>
                    <li class="navbar-brand"><a href="#kontak">Contact</a> </li>
                    <li class="navbar-brand"><a href="{% url 'home:interests' %}">Interests</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
                </div>
        </header>

        <section class="container1">
        <section class="landing" id="mendarat">
            <div class="center_text">
                <h1>Welcome to my website!</h1>
                <h2>Wanna know more about me?</h2>
            </div>
            <button class = "tombol1"><a href ="#aku">Click Here</a></button>
        </section>

        <section class="about" id="aku">
            <div class="foto2">
                <img src="{% static "image/sena.jpg" %}" class="sena" alt="">
            </div>
            <div class="akudanjudul">
                <div class="judul2"><p>About Me</p></div>
                <div class="tulisanaku">
                Hello! My Name is Ariasena Cahya Ramadhani. People often call me Sena. I am currently studying Computer Science at University of Indonesia. I love speaking with other people and also working as a team. I am interested in psychology and esports.
                </div>
            </div>

        </section>

        <section class="education" id="ilmu">
            <div class="foto3">
                <img src="{% static "image/pacil7.PNG" %}" class="fasilkom" alt="">
            </div>
            <div class="akudanjudul2">
                <div class="judul3"><div class="all_edu">
                    <div class="ui">
                        <p class="gelar">Bachelor of Computer Science</p>
                        <p class="institusi">University of Indonesia</p>
                    </div>
                    <div class="sma">
                        <p class="gelar">High School Diploma</p>
                        <p class="institusi">SMAN 99 Jakarta</p>
                    </div>
                    <div class="smp">
                        <p class="gelar">Middle School</p>
                        <p class="institusi">SMP Islam PB Soedirman</p>
                    </div>
                    <div class="sd">
                        <p class="gelar">Elementary School</p>
                        <p class="institusi">SD Islam PB Soedirman</p>
                    </div>
                </div></div>
                <div class="tulisanaku2">
                    Education
                </div>
            </div>
        </section>

        <section class="experiences" id="pengalaman">
            <div class="foto2">
                <img src="{% static "image/compe.jpg" %}" class="fasilkom" alt="">
            </div>
            <div class="akudanjudul">
                <div class="judul2"><p>Experiences</p>
                </div>
                <div class="pengalaman">
                    <div class="all_exp">
                         <div class="ui">
                             <p class="gelar">Human Resources Staff</p>
                             <p class="institusi">BEM Fasilkom UI</p>
                         </div>
                        <div class="sma">
                            <p class="gelar">Human Resources of Games and Competition</p>
                            <p class="institusi">Perak Fasilkom</p>
                        </div>
                        <div class="smp">
                            <p class="gelar">Indie Game Ignite Staff</p>
                            <p class="institusi">Compfest 12</p>
                        </div>
                        <div class="sd">
                            <p class="gelar">Liason Officer</p>
                            <p class="institusi">Wisuda Ganjil Fasilkom UI</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

         <section class="skills" id="kemampuan">
            <div class="foto3">
                <img src="{% static "image/skills1.PNG" %}" class="fasilkom" alt="">
            </div>
            <div class="akudanjudul2">
                <div class="judul3"><div class="all_edu">
                    <div class="ui">
                        <img src="{% static "image/css-3.png" %}" class="skillsgambar" alt="">
                        <h2>CSS</h2>
                    </div>
                    <div class="sma">
                        <img src="{% static "image/html-5.png" %}" class="skillsgambar" alt="">
                        <h2>HTML</h2>
                    </div>
                    <div class="smp">
                        <img src="{% static "image/java.png" %}" class="skillsgambar" alt="">
                        <h2>Java</h2>
                    </div>
                    <div class="sd">
                        <img src="{% static "image/python.png" %}" class="skillsgambar" alt="">
                        <h2>Python</h2>
                    </div>
                </div></div>
                <div class="tulisanaku2">
                    Skills
                </div>
            </div>
        </section>

        </section>
    <section class="contact" id="kontak">
            <ul class="icons">
                <li><a href="https://www.instagram.com/ariasenacahya/" target="_blank"> <img src="{% static "image/instagram (1).png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
                <li><a href="https://twitter.com/ddelvo45" target="_blank"> <img src="{% static "image/twitter (1).png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
                <li><a href="https://www.linkedin.com/in/ariasena-cahya-ramadhani-98388a179/" target="_blank"> <img src="{% static "image/linkedin.png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
                <li><a href="https://steamcommunity.com/id/poopfodays/" target="_blank"> <img src="{% static "image/steam(1).png" %}"
                                                                                             class= "logo_kontak" alt = ""> </a> </li>
            </ul>
    </section>

    <section class="footer">
            <h1>2020 Faculty of Computer Science University of Indonesia</h1>
    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static "jscript/app.js" %}"></script>
</body>
</html>

templates/home/listmatkul.html
{% extends 'home/base.html' %}
{% load static %}
{% block navigation %}
     <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav6"><a href="{% url 'home:namamatkul' %}">Mata Kuliah</a></li>
                    <li class="nav7"><a href="{% url 'home:matakuliah' %}">Isi Form</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
            </div>
{% endblock %}
{% block content%}
    <section class="container5">
        <header class="containerJudul">
            <h1>Detail mata kuliah yang sudah terdaftar</h1>
        </header>
        <section class="containerMatkul">
        <table class="table table-dark table-bordered table-striped">
        <thead>
            <tr>
              <th scope="col">Mata Kuliah</th>
              <th scope="col">Nama Dosen</th>
              <th scope="col">Jumlah SKS</th>
              <th scope="col">Deskripsi Kuliah</th>
              <th scope="col">Tahun</th>
              <th scope="col">Kelas</th>
              <th scope="col">Hapus</th>
            </tr>
        </thead>
            {% for kuliah in all %}
                <tr>
                    <td>{{ kuliah.matkul }}</td>
                    <td>{{ kuliah.dosen }}</td>
                    <td>{{ kuliah.jumlahSks }}</td>
                    <td>{{ kuliah.deskripsi }}</td>
                    <td>{{ kuliah.tahun }}</td>
                    <td>{{ kuliah.kelas }}</td>
                    <td><a href="{% url 'home:hapusMatkul' kuliah.id %}"><button type="button"><img src="{% static "image/delete.svg" %}" class="Hapus" alt="Logo_UI"></button></a></td>
                </tr>
            {% endfor %}
        </table>
        </section>
        <section class="blankDiv">

        </section>
    </section>
{% endblock %}

templates/home/matakuliah.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block navigation %}
     <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav6"><a href="{% url 'home:matakuliah' %}">Mata Kuliah</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
            </div>
{% endblock %}
{% block content %}
    <section class="container3">
        <header class="containerJudul">
            <h1>Daftarkan Mata Kuliah di Kolom Ini</h1>
        </header>
        <section class="containerForm">
         <form action="" method="post">
              {% csrf_token %}
              {{ form|crispy }}
             <input type="submit" value="Submit" class="btn" />
             <button class="btnMatkul"><a href="{% url 'home:namamatkul' %}">List Matkul</a></button>
         </form>
    </section>
    </section>
{% endblock %}

templates/home/namamatkul.html
{% extends 'home/base.html' %}
{% load static %}
{% block navigation %}
     <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav6"><a href="{% url 'home:namamatkul' %}">Mata Kuliah</a></li>
                    <li class="nav7"><a href="{% url 'home:matakuliah' %}">Isi Form</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
            </div>
{% endblock %}

{% block content %}
    <section class="container5">
        <header class="containerJudul">
            <h1>Daftar mata kuliah yang sudah terdaftar</h1>
        </header>
        <section class="containerMatkul">
        <table class="table table-dark table-bordered table-striped">
        <thead>
            <tr>
              <th scope="col">Mata Kuliah</th>
            </tr>
        </thead>
            {% for kuliah in all %}
                <tr>
                    <td><a href="{% url 'home:listmatkul' %}">{{ kuliah.matkul }}</a></td>
                </tr>
            {% endfor %}
        </table>
        </section>
        <section class="blankDiv">

        </section>
    </section>
{% endblock %}

templates/home/terimakasih.html
{% extends 'home/base.html' %}
{% load static %}
{% block navigation %}
     <img src="{% static "image/makara-ui-fasilkom.png" %}" class="Logo" alt="Logo_UI">
            <nav>
                <ul class="nav_links">
                    <li class="nav1"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav6"><a href="{% url 'home:matakuliah' %}">Mata Kuliah</a></li>
                </ul>
            </nav>
            <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
            </div>
{% endblock %}

{% block content %}
    <section class="container4">
         <header class="containerJudul">
            <h1>Terimakasih sudah mengisi form</h1>
             <h2>Tekan tombol dibawah ini untuk mengisi ulang</h2>
        </header>
        <section class="buttonContainer">
            <a href="{% url 'home:matakuliah' %}"><button type="button" >Kembali</button></a>
        </section>

    </section>

{% endblock %}